version: 0.2

env:
  variables:
    GO_VERSION: 1.10.1
    SRC_DIR: src/github.com/abc123931
    PROJECT_NAME: test-project

phases:

  install:
    commands:
      # clean go repo
      - rm -rf /usr/local/go/

      # Install Golang
      - curl -sSL -o /tmp/go.tar.gz https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
      - tar -C /usr/local -xzf /tmp/go.tar.gz
      - export GOPATH=${HOME}/go && echo ${GOPATH}
      - export PATH=/usr/local/go/bin:${GOPATH}/bin:${PATH} && echo ${PATH}
      - type go && go version

      # Install golint
      - go get -u github.com/golang/lint/golint

      # install dep
      - go get -u github.com/golang/dep/cmd/dep

  pre_build:
    commands:

      - mkdir -p ${GOPATH}/${SRC_DIR}
      - ln -s "${CODEBUILD_SRC_DIR}" "${GOPATH}/${SRC_DIR}/${PROJECT_NAME}"
      - cd ${GOPATH}/${SRC_DIR}/${PROJECT_NAME}

      # Fetch all dependencies
      - dep ensure

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Check for common Go application problems with 'go tool vet'
      #- go tool vet .

      # Run all tests included with our application
      - go test ./hello-world/

  build:
    commands:

      # Build our go application
      - cd hello-world
      - go build -o main
      - cd ../

      # Copy static assets to S3, and package application with AWS CloudFormation/SAM
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml
